"""Shared protocol and runtime constants."""

BYTES_PER_KIBIBYTE = 1024
BYTES_PER_MEBIBYTE = BYTES_PER_KIBIBYTE * BYTES_PER_KIBIBYTE
DEFAULT_NAME_TEMPLATE = "{title} [{id}].{ext}"
DEFAULT_RETRIES = 4
DEFAULT_REQUEST_TIMEOUT_SECONDS = 30
DEFAULT_WORKERS = 8
FILE_COPY_BUFFER_BYTES = BYTES_PER_MEBIBYTE
HTTP_RANGE_HEADER = "Range"
HTTP_RANGE_UNIT = "bytes"
HTTP_OK = 200
HTTP_PARTIAL_CONTENT = 206
HTTP_SCHEMES = frozenset({"http", "https"})
HTTP_URL_PREFIXES = ("http://", "https://")
M3U8_SUFFIX = ".m3u8"
MAX_RETRY_DELAY_SECONDS = 5
MAX_WORKERS = 16
MP4_SUFFIX = ".mp4"
RESOLUTION_QUALITIES = frozenset({"1080", "720", "480", "360"})
SEGMENT_TRANSFORM_SUPJAV_FAKE_PNG = "supjav_fake_png"
TEMPORARY_MP4_SUFFIX = ".part.mp4"
